name: try_auth_suba
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  cv: ^0.2.18+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_resume_template: ^1.2.0
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  get_storage: ^2.1.1
  supabase_flutter: ^2.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - .env
    - image/
  uses-material-design: true
