name: cv_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  introduction_screen: ^3.1.12
  supabase_flutter: ^2.3.4
  flutter_resume_template: ^1.2.0
  google_fonts: ^4.0.5
  get_storage: ^2.1.1
  get_it: ^7.6.7
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - .env
